Pandas Library:

Useful for Data Processing & Analysis

Pandas Data Frame:

Pandas DataFrame is two-dimensional tabular data structure with labeled axes (rows and columns).

In [74]:
# importing the pandas library
import pandas as pd
import numpy as np

Creaating a Pandas DataFrame

In [60]:
# pandas DataFrame
boston_df=pd.read_csv("BostonHousing.csv")

In [62]:
type(boston_df)

pandas.core.frame.DataFrame

In [14]:
boston_df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [66]:
boston_df.shape #(row,col)

(506, 14)

In [68]:
# csv file to pandas df
diabetes_df = pd.read_csv("diabetes.csv")

In [70]:
type(diabetes_df)

pandas.core.frame.DataFrame

In [30]:
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [72]:
diabetes_df.shape

(768, 9)

Loading the data from a excel file to a Pandas DataFrame:

pd.read_excel('file path')

Exporting a DataFrame to a csv file

Exporting the Pandas DataFrame to an excel File:

df.to_excel('filename')

In [86]:
np.random.rand(10) #1 dim

array([0.25103874, 0.63479144, 0.81000329, 0.12930902, 0.28517481,
       0.78278701, 0.90813077, 0.75528253, 0.73391481, 0.59121149])

In [88]:
np.random.rand(5,5) #2 dim

array([[0.80772536, 0.54464397, 0.31232362, 0.17445867, 0.35775448],
       [0.77384109, 0.77851273, 0.48530523, 0.07458958, 0.94913437],
       [0.06790836, 0.35876069, 0.0209329 , 0.72538024, 0.43925779],
       [0.31817804, 0.7536177 , 0.94696696, 0.3972087 , 0.9218767 ],
       [0.18437672, 0.92249248, 0.55361498, 0.33428768, 0.42724149]])

In [92]:
np.random.rand(3,2,5) #3 dim

array([[[0.78067825, 0.40283033, 0.6274667 , 0.87345974, 0.66111528],
        [0.70548826, 0.40603198, 0.11293358, 0.37525023, 0.9901927 ]],

       [[0.51466171, 0.13075665, 0.80653741, 0.33108056, 0.73480403],
        [0.19729871, 0.91676667, 0.5896224 , 0.50502284, 0.44737521]],

       [[0.74491556, 0.11334782, 0.09686222, 0.59815444, 0.40453381],
        [0.25755415, 0.22328167, 0.4024461 , 0.15900711, 0.90410522]]])

In [94]:
rand_data=np.random.rand(5,5)*50 #range-->(1 to n)  

In [98]:
print(rand_data)
print(type(rand_data))

[[25.41038275 47.2899442  30.66267478 22.27737666 30.19459024]
 [37.50378979  3.72126688  1.39733939 27.2124146  37.01095857]
 [23.9714885   7.44120531 26.85093713 16.41185052 36.09844687]
 [14.71085359 17.78784354 16.80537514 35.93165258 49.94662346]
 [48.00446899 25.03823216 20.4733079  25.14703133 37.662568  ]]
<class 'numpy.ndarray'>


In [106]:
# creating a DatFrame with random values
random_df = pd.DataFrame(np.random.rand(20,10)*10)
rand_df2=pd.DataFrame(rand_data)

In [104]:
random_df.head()

0         1         2         3         4         5         6  \
0  1.464001  8.645891  0.605951  3.193383  8.894916  8.916124  7.538147   
1  0.561702  2.520766  4.581795  5.578502  3.468570  5.513048  0.917620   
2  0.065194  5.043385  2.380484  1.591089  1.714474  0.514210  9.790358   
3  0.048253  8.207316  8.853879  4.532201  1.675846  1.907684  2.285452   
4  7.628034  4.522058  9.534117  1.698791  0.229150  8.032941  6.322353   

          7         8         9  
0  0.490461  6.359355  3.438861  
1  6.572731  4.634979  5.496392  
2  7.478479  7.324998  6.286992  
3  8.097462  2.492703  5.236672  
4  8.065321  7.104450  0.460718

In [108]:
rand_df2.head()

0          1          2          3          4
0  25.410383  47.289944  30.662675  22.277377  30.194590
1  37.503790   3.721267   1.397339  27.212415  37.010959
2  23.971489   7.441205  26.850937  16.411851  36.098447
3  14.710854  17.787844  16.805375  35.931653  49.946623
4  48.004469  25.038232  20.473308  25.147031  37.662568

In [110]:
random_df.shape

(20, 10)

Inspecting a DataFrame

In [113]:
#finding the number of rows & columns
boston_df.shape

(506, 14)

In [115]:
# first 5 rows in a DataFrame
boston_df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [119]:
# last 5 rows of the DataFrame
boston_df.tail(12)

crim   zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
494  0.27957  0.0   9.69     0  0.585  5.926  42.6  2.3817    6  391     19.2   
495  0.17899  0.0   9.69     0  0.585  5.670  28.8  2.7986    6  391     19.2   
496  0.28960  0.0   9.69     0  0.585  5.390  72.9  2.7986    6  391     19.2   
497  0.26838  0.0   9.69     0  0.585  5.794  70.6  2.8927    6  391     19.2   
498  0.23912  0.0   9.69     0  0.585  6.019  65.3  2.4091    6  391     19.2   
499  0.17783  0.0   9.69     0  0.585  5.569  73.5  2.3999    6  391     19.2   
500  0.22438  0.0   9.69     0  0.585  6.027  79.7  2.4982    6  391     19.2   
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273     21.0   

          b  lstat  medv  
494  396.90  13.59  24.5  
495  393.29  17.60  23.1  
496  396.90  21.14  19.7  
497  396.90  14.10  18.3  
498  396.90  12.92  21.2  
499  395.77  15.10  17.5  
500  396.90  14.33  16.8  
501  391.99   9.67  22.4  
502  396.90   9.08  20.6  
503  396.90   5.64  23.9  
504  393.45   6.48  22.0  
505  396.90   7.88  11.9

In [121]:
# informations about the DataFrame
boston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [123]:
# finding the number of missing values
boston_df.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [126]:
# counting the values based on the labels
diabetes_df.value_counts('Outcome')

Outcome
0    500
1    268
Name: count, dtype: int64

In [128]:
boston_df.value_counts("rad")

rad
24    132
5     115
4     110
3      38
6      26
2      24
8      24
1      20
7      17
Name: count, dtype: int64

In [130]:
boston_df.value_counts("crim") # inefficient, not for the continuous 

crim
14.33370    2
0.01501     2
1.05393     1
1.41385     1
1.38799     1
           ..
0.11069     1
0.11027     1
0.10959     1
0.10793     1
88.97620    1
Name: count, Length: 504, dtype: int64

In [132]:
# group the values based on the mean
diabetes_df.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

Statistical Measures

In [134]:
# count or number of values
boston_df.count()

crim       506
zn         506
indus      506
chas       506
nox        506
rm         506
age        506
dis        506
rad        506
tax        506
ptratio    506
b          506
lstat      506
medv       506
dtype: int64

In [ ]:
# mean value - column wise
boston_df.mean()

CRIM         3.613524
ZN          11.363636
INDUS       11.136779
CHAS         0.069170
NOX          0.554695
RM           6.284634
AGE         68.574901
DIS          3.795043
RAD          9.549407
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.653063
dtype: float64

In [ ]:
# standard deviation - column wise
boston_df.std()

CRIM         8.601545
ZN          23.322453
INDUS        6.860353
CHAS         0.253994
NOX          0.115878
RM           0.702617
AGE         28.148861
DIS          2.105710
RAD          8.707259
TAX        168.537116
PTRATIO      2.164946
B           91.294864
LSTAT        7.141062
dtype: float64

In [ ]:
# minimum value
boston_df.min()

CRIM         0.00632
ZN           0.00000
INDUS        0.46000
CHAS         0.00000
NOX          0.38500
RM           3.56100
AGE          2.90000
DIS          1.12960
RAD          1.00000
TAX        187.00000
PTRATIO     12.60000
B            0.32000
LSTAT        1.73000
dtype: float64

In [ ]:
# maximum value
boston_df.max()

CRIM        88.9762
ZN         100.0000
INDUS       27.7400
CHAS         1.0000
NOX          0.8710
RM           8.7800
AGE        100.0000
DIS         12.1265
RAD         24.0000
TAX        711.0000
PTRATIO     22.0000
B          396.9000
LSTAT       37.9700
dtype: float64

In [140]:
# all the statistical measures about the dataframe
boston_df.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

Manipulating a DataFrame

In [148]:
# adding a column to a dataframe
boston_df['Price'] = np.random.rand(len(boston_df["crim"]))

In [150]:
boston_df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv     Price  
0  396.90   4.98  24.0  0.707459  
1  396.90   9.14  21.6  0.471027  
2  392.83   4.03  34.7  0.093714  
3  394.63   2.94  33.4  0.760320  
4  396.90   5.33  36.2  0.815132

In [152]:
# removing a row
boston_df.drop(index=3, axis=0) # axis=0-->row, axis=1-->col

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
5    0.02985   0.0   2.18     0  0.458  6.430  58.7  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv     Price  
0       15.3  396.90   4.98  24.0  0.707459  
1       17.8  396.90   9.14  21.6  0.471027  
2       17.8  392.83   4.03  34.7  0.093714  
4       18.7  396.90   5.33  36.2  0.815132  
5       18.7  394.12   5.21  28.7  0.404797  
..       ...     ...    ...   ...       ...  
501     21.0  391.99   9.67  22.4  0.401833  
502     21.0  396.90   9.08  20.6  0.223835  
503     21.0  396.90   5.64  23.9  0.657967  
504     21.0  393.45   6.48  22.0  0.464805  
505     21.0  396.90   7.88  11.9  0.884798  

[505 rows x 15 columns]

In [154]:
# drop a column
boston_df.drop(columns='Price', axis=1)

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [ ]:
# locating a row using the index value
boston_df.iloc[2]

CRIM         0.02729
ZN           0.00000
INDUS        7.07000
CHAS         0.00000
NOX          0.46900
RM           7.18500
AGE         61.10000
DIS          4.96710
RAD          2.00000
TAX        242.00000
PTRATIO     17.80000
B          392.83000
LSTAT        4.03000
Price       34.70000
Name: 2, dtype: float64

In [ ]:
# locating a particular column
print(boston_df.iloc[:,0])  # first column
print(boston_df.iloc[:,1])  # second column
print(boston_df.iloc[:,2])  # third column
print(boston_df.iloc[:,-1]) # last column

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64
0      18.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
501     0.0
502     0.0
503     0.0
504     0.0
505     0.0
Name: ZN, Length: 506, dtype: float64
0       2.31
1       7.07
2       7.07
3       2.18
4       2.18
       ...  
501    11.93
502    11.93
503    11.93
504    11.93
505    11.93
Name: INDUS, Length: 506, dtype: float64
0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: Price, Length: 506, dtype: float64


Correlation:

1. Positive Correlation
2. Negative Correlation

In [156]:
boston_df.corr()

crim        zn     indus      chas       nox        rm       age  \
crim     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219247  0.352734   
zn      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
indus    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
chas    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
nox      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
rm      -0.219247  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
age      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
dis     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
rad      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
tax      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
ptratio  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
b       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
lstat    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
medv    -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   
Price    0.011169  0.060600 -0.071337 -0.085357 -0.016898  0.033954 -0.056194   

              dis       rad       tax   ptratio         b     lstat      medv  \
crim    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305   
zn       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445   
indus   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725   
chas    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260   
nox     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321   
rm       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360   
age     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955   
dis      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929   
rad     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626   
tax     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536   
ptratio -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787   
b        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461   
lstat   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663   
medv     0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000   
Price    0.011986  0.014390  0.003873  0.019182 -0.036559  0.003112  0.013941   

            Price  
crim     0.011169  
zn       0.060600  
indus   -0.071337  
chas    -0.085357  
nox     -0.016898  
rm       0.033954  
age     -0.056194  
dis      0.011986  
rad      0.014390  
tax      0.003873  
ptratio  0.019182  
b       -0.036559  
lstat    0.003112  
medv     0.013941  
Price    1.000000